### ISSUE TITLE
Form: Select market, side and leverage

### ISSUE THREAD

**Issue by KittyLomas** [tracer-protocol/pools-client#286]
As a retail trader
I want to be able to input the market, side and leverage I'm after
So that I can view the pool token I want to trade that will allow me to receive exposure to my desired market

### **A/Cs**

**Scenario 1: No wallet connected, user connects wallet**

Given I have not connected my wallet
and I'm on the 'tokens' page
When I select 'Connect my wallet'
Then the system triggers me to connect my Web3 wallet

**Scenario 2: No wallet connected, user fills out form**

Given I have not connected my wallet
and I'm on the 'tokens' page
When I try to select market, side and power leverage
The system displays the available markets, sides and leverages and let's me fill it out

**Scenario 3: User has connected wallet, selects 'Take me to Balancer' with completed form**

Given I have successfully connected my wallet
and I'm on the 'tokens' page, with the form completed
When I select 'Take me to Balancer'
The system opens a new tab to [balancer.fi](http://balancer.fi) with the respective pool token selected

**Scenario 4: User has connected wallet, selects 'Take me to Balancer' without completed form**

Given I have successfully connected my wallet
and I'm on the 'tokens' page, without the form completed
When I try to select 'Take me to Balancer'
The system won't let me as the button is inactive

**Comment by dospore** [comment]
Can you check that this has not been completed already and is in develop https://deploy-preview-287--tracer-pools.netlify.app/
