### ISSUE TITLE
Remove 'On' that prefixes the subheadings under 'Effective Leverage' and 'Token Price'

### ISSUE THREAD

**Issue by KittyLomas** [tracer-protocol/pools-client#326]
On the tables we currently say:

Effective Leverage
On Gains    On Losses

Token Prices
On Tracer    On Balancer

Can you please cut all of the 'On's so that it's:

Effective Leverage
Gains    Losses

Token Prices
Tracer    Balancer

**Comment by dospore** [comment]
Link to #283
