### ISSUE TITLE
Fix the spacing of the two tables: 'Next Rebalance' and 'Last Rebalance'

### ISSUE THREAD

**Issue by KittyLomas** [tracer-protocol/pools-client#349]
If you switch between Next Rebalance and Last Rebalance,  it's pretty jarring and hard to adjust to the spacing and map the data to the metric. Can you please fix the spacing of the two tables, so that switching between the tables is seamless. See the prototype here  (play with the toggle) for how it should be: https://www.figma.com/proto/PFSmfgo2pKuDsftwOyC7pn/Tracer-Web-3.0?page-id=5203%3A250692&node-id=5274%3A251169&viewport=394%2C48%2C0.37&scaling=min-zoom&starting-point-node-id=5274%3A251169&show-proto-sidebar=1

**Comment by dospore** [comment]
Link to #283
