### ISSUE TITLE
Add toggle to allow value change to be expressed as a percent or a number

### ISSUE THREAD

**Issue by KittyLomas** [tracer-protocol/pools-client#356]
Currently, we are showing the changes in values since the last rebalance as a percentage. It's likely that users will like to see the change expressed in a number as well. (For example, if the TVL has changed from $4,000 to $2,000, we could show **both** -50% or -$2,000). 

Designs: https://www.figma.com/file/PFSmfgo2pKuDsftwOyC7pn/Tracer-Web-3.0?node-id=5628%3A277178

**Comment by dospore** [comment]
@KittyLomas will need mobile designs as well since that entire nav collapses on mobile

**Comment by KittyLomas** [comment]
@dospore see all designs here (light dark, mobile desktop)
Al has slightly changed the toggle to look a little better https://www.figma.com/file/PFSmfgo2pKuDsftwOyC7pn/Tracer-Web-3.0?node-id=5234%3A296859

**Comment by dospore** [comment]
> @dospore see all designs here (light dark, mobile desktop) Al has slightly changed the toggle to look a little better https://www.figma.com/file/PFSmfgo2pKuDsftwOyC7pn/Tracer-Web-3.0?node-id=5234%3A296859

so hide the toggle on mobile??

**Comment by KittyLomas** [comment]
@dospore on mobile, add this little filter icon. When a user selects the filter icon, the market filter and the % # show (see designs to the right for that) 
https://www.figma.com/file/PFSmfgo2pKuDsftwOyC7pn/Tracer-Web-3.0?node-id=5320%3A302437

**Comment by KittyLomas** [comment]
@dospore bugs:

- [ ] The percent <> numerical values don't seem to add up. 0.4% of $47,779.70 is $191.12, not $188.91
![image](https://user-images.githubusercontent.com/32585489/145501188-e51cf846-76d5-4284-8499-1d38ed517579.png)
![image](https://user-images.githubusercontent.com/32585489/145501201-15ca83ac-1041-4bc0-9e92-9981b64c735c.png). This is the case for quite a few (base asset, TVL for each pool and side, etc.). 
- [ ] Can we please increase the significant figures for the update in pool skew (when showing the 'numerical' chage). I'm assuming they are all changing less than 0.01, so the interface is rounding them all up. Can we please show 3 sig figs, rather than 2. (It might be best to show 4 even, what're your thoughts?).  
- [ ] Can we update the text on the toggle from 'Numerical' to 'Number' please
