### ISSUE TITLE
Change in TVL for each pool /= Change in TVL for each side

### ISSUE THREAD

**Issue by KittyLomas** [tracer-protocol/pools-client#357]
![image](https://user-images.githubusercontent.com/32585489/144778767-e5fb145a-13ca-491e-932a-51fe2798888c.png)

- Change in TVL is 0% for all pools, yet the TVL of each side has changed. Is this a bug?

**Comment by dospore** [comment]
No, this just means no new mints or burns. The individual pool values change due to the value transfer
