### ISSUE TITLE
Add percent changes to 'Last Rebalance' table

### ISSUE THREAD

**Issue by KittyLomas** [tracer-protocol/pools-client#361]
Currently, we're only showing the values of the pools at the last rebalance. This data on it's own is not very useful. Users are likely going to want to know what HAPPENED last rebalance, i.e., how much did the TVL increase, how much did the base change in price. Therefore, can you please add the percent (and numerical) changes for each, comparing the last rebalance, to the rebalance before it.

**Comment by dospore** [comment]
@ScaredIbis this can either come from the TVL endpoint or from a summation of commits from lastRebalance - updateInterval to lastRebalance, can you link them in here

**Comment by KittyLomas** [comment]
@dospore this ticket isn't finished. Few things I noticed:

- [ ] Fix NaN issue 
![image](https://user-images.githubusercontent.com/32585489/145147603-37acec49-0ce5-48d2-ae1e-69875fd81ad4.png)

- [ ] Add change in TVL to the right of the values
![image](https://user-images.githubusercontent.com/32585489/145147698-926263ff-cea6-4566-b7b7-4c07be372162.png)

- [ ] Add change in skew to the right of the values 
![image](https://user-images.githubusercontent.com/32585489/145147811-81d2a7ba-9c62-4028-82b3-e6ad833a3980.png)


- [ ] Add change in token price to the right of the values 
![image](https://user-images.githubusercontent.com/32585489/145147783-aa227043-6f1b-4dc2-a76c-6916620e90a1.png)

**Comment by KittyLomas** [comment]
@dospore bugs:

- [ ] It's currently showing incorrect values on the 'last rebalance' table
![image](https://user-images.githubusercontent.com/32585489/145496046-7bd8f209-f470-45af-959a-63f7d837ce70.png). TVL, base price, etc. should not all be zero. It's also showing 'NaN' for the 'percent' shift. Once you've fixed this, i'll be able to test the  ticket
