### ISSUE TITLE
Tooltip: up/down update to values on the 'Next Rebalance' table

### ISSUE THREAD

**Issue by KittyLomas** [tracer-protocol/pools-client#362]
We need to add tooltips to the (up/down) values that represents how much each metric has changed in the given interval (on both the next and last rebalance tables). 

- [x] Added to the values on the 'Next Rebalance' table:
The [INSERT METRIC] is currently [INSERT % OR #] [greater than / less than] it was at the last rebalance for the [INSERT POOL TICKER] pool.
Example: _The TVL is currently 1.12% greater than it was at the last rebalance for the 1-BTC/USD pool._ 

- [x] Added to the values on the 'Last Rebalance' table
The [INSERT METRIC] [increased / decreased] by [INSERT % OR #] during the last rebalance for the [INSERT POOL TICKER] pool. 
Example: _The TVL increased by 1.12% during the last rebalance for the 1-BTC/USD pool._

**Comment by dospore** [comment]
To confirm the metrics would be 

- TVL
- Skew
- Base price
- Token price

@KittyLomas

**Comment by KittyLomas** [comment]
@dospore 
We need it for:

- Base Price
- TVL (USDC)
- Skew
- TVL for each token
- Token Price (USDC) 

See designs:
https://www.figma.com/file/PFSmfgo2pKuDsftwOyC7pn/Tracer-Web-3.0?node-id=5247%3A247077

**Comment by dospore** [comment]
> @dospore We need it for:
> 
> * Base Price
> * TVL (USDC)
> * Skew
> * TVL for each token
> * Token Price (USDC)
> 
> See designs: https://www.figma.com/file/PFSmfgo2pKuDsftwOyC7pn/Tracer-Web-3.0?node-id=5247%3A247077

So you want it to read

The Token Price (USDC) is currently 1.12% greater than it was at the last rebalance for the 1-BTC/USD pool.

**Comment by KittyLomas** [comment]
The long token price increased by 1.12% during the last rebalance for the 1-BTC/USD pool.

The short token price decreased by $4.2 during the last rebalance for the 1-BTC/USD pool. 

The long TVL increased by $40,000 during the last rebalance for the 1-BTC/USD pool.

@dospore for the % shift for the tokens, can you please prefix it with [long/short]

**Comment by KittyLomas** [comment]
@dospore bugs to fix

- [ ] The tooltip for values in the 'POOLS' section of the table should not have the [long / short] prefix. Please remove it. I.e., below should read 'The base price is currently 0.05% greater than it was at the last rebalance for the 1-ETH/USD pool. 
![image](https://user-images.githubusercontent.com/32585489/145496941-b0dad5fb-089c-4ca8-ba87-96a41b2b64f7.png)

- [ ] Can you please update all of the tooltips from "... the last rebalance **for** the [POOL] pool" to 
"...the last rebalance **of** the [POOL] pool." (i.e.., change 'for' to 'of)

- [ ] We need to alter the tooltip slightly for values that have not changed (i.e., 0% change). 
Can you please update the format for the **POOL values** on the **Next Rebalance** table to be: 
- "The [insert metric] has not changed since the last rebalance of the [insert pool metric] pool." 
For example: _The base price has not changed since the last rebalance of the 1-BTC/USD pool._ 

Can you please update the format of the **POOL TOKEN values** on the **Next Rebalance** table to be:
- "The [long/short] [insert metric] has not changed since the last rebalance of the [insert pool metric] pool." 
For example: _The long TVL has not changed since the last rebalance of the 1-BTC/USD pool._ 

Can you please update the format of the **POOL values** on the **Last Rebalance** table to be:
- "The [insert metric] did not change during the last rebalance of the [insert pool ticker] pool.
For example: _The base price did not change during the last rebalance of the 1-BTC/USD pool._

Can you please update the format of the **POOL TOKEN values** on the **Last Rebalance** table to be:
- "The [long/short] [insert metric] did not change during the last rebalance of the [insert pool ticker] pool.
For example: _The long TVL did not change during the last rebalance of the 1-BTC/USD pool._

- [ ] Can you please uncapitlize 'Short' and 'Long', and all of the metrics. Rather than 'Base Price' it should just be 'base price', etc.

**Comment by KittyLomas** [comment]
Final fixes:

- [ ] On the 'Next Rebalance' table, you're missing the 'long' prefix: 
![image](https://user-images.githubusercontent.com/32585489/145735083-dab8aa0a-39b8-41c9-a664-deb6ee57260e.png)
I.e., it should be 'The long TVL has not changed...'

I can't check the fixes on the other table as it's still saying NaN as the % of all the information 
![image](https://user-images.githubusercontent.com/32585489/145735136-8894c134-2dfb-43cd-9736-654d35ba87e8.png)
