### ISSUE TITLE
Volatility decay warning

### ISSUE THREAD

**Issue by KittyLomas** [tracer-protocol/pools-client#365]
Users keep getting rekt due to volatility decay. We are about to launch new markets and might attract new users. We need to warn these new (and existing) users  not to hold the tokens  long-term. 

Please put this warning on all pages. Once a user selects 'x' during one session, it should be removed on all pages. It should appear in their next session though.

Designs: https://www.figma.com/file/Gh6WzO8gLZWDmTvRbw8ikm/Tracer---V2?node-id=5286%3A180743

**Comment by dospore** [comment]
@KittyLomas What should the href link to??
