### ISSUE TITLE
Final Fixes

### ISSUE THREAD

**Issue by KittyLomas** [tracer-protocol/pools-client#372]
Final fixes:
- [x] The market price is not an 'expected' value. It's the value from the oracle. Can you please remove the expected from this tooltip. 
![image](https://user-images.githubusercontent.com/32585489/146293661-b99b7a65-1283-4352-bb13-7670fa5ff582.png).

- [x] Please add (USD) to the MARKET PRICE column heading. "MARKET PRICE (USD)"
- [x] ![image](https://user-images.githubusercontent.com/32585489/146294174-3307b490-a064-43d2-a04d-b26d3a5d0321.png)
It is saying that the market price did not change at all during the last pool rebalance (on arbitrum mainnet). This must be wrong?

- [x] Queued burns table isn't showing my queued burn on Arbitrum testnet
![image](https://user-images.githubusercontent.com/32585489/146294690-2d59c586-48f7-4c04-ae41-4efcb7f7349c.png)

- [x] On Arbitrum testnet it says the minimum burn order size is $12,751 
![image](https://user-images.githubusercontent.com/32585489/146294993-af8c7df5-18b8-438c-9bc9-606638dcccc0.png)

- [x] Can you please make the volatility decay warning and the beta warning also appear on the pools page

**Comment by ScaredIbis** [comment]
@KittyLomas I've updated the column header from `Market Price` to `Index Price (USD)` for now but keep in mind when we have pools with underlying feeds that are not USD based this kind of wording will need to change throughout

**Comment by dospore** [comment]
@KittyLomas the minimumTokens calc seems to be whack on current version of prod (on testnet) as well. I havent changed that calc so will have to debug with financial eng guys
