### ISSUE TITLE
Portfolio

### ISSUE THREAD

**Issue by KittyLomas** [tracer-protocol/pools-client#410]
# Designs

- Portfolio overview: https://www.figma.com/file/Gh6WzO8gLZWDmTvRbw8ikm/Tracer-Style-Guide-%26-Components?node-id=6093%3A242078
- Pending Flip: https://www.figma.com/file/Gh6WzO8gLZWDmTvRbw8ikm/Tracer-Style-Guide-%26-Components?node-id=6107%3A234317
- Flip History: https://www.figma.com/file/Gh6WzO8gLZWDmTvRbw8ikm/Tracer-Style-Guide-%26-Components?node-id=5978%3A205608

**Comment by dospore** [comment]
Ticket has been broken down into smaller tickets
