### ISSUE TITLE
Release 1.2 - Bugs from Testing

### ISSUE THREAD

**Issue by elliot86** [tracer-protocol/pools-client#426]
Based on current testing:

- [ ] Countdown timers don't match between toasts and table view
![countdown-timer](https://user-images.githubusercontent.com/8314736/149742827-f6a4a3b1-3eb5-4241-ad98-df6ff64136f6.gif)

- [ ] Expected Price is usually $0, which affects the price through the whole process.
![expected](https://user-images.githubusercontent.com/8314736/149741172-87b310e5-36e7-4b20-a4e2-abd17a7fc4ed.png)

- [ ] 'View on Arbiscan' only appears on toast prior to confirming in web3 wallet, then changes to view order. It shouldn't disappear.
![view-token-on-arbiscan](https://user-images.githubusercontent.com/8314736/149741524-af4fbb68-29e7-433b-8d74-7328acbed221.gif)

No toast notifications after queued toaster reaches 0 and disappears.
- [ ] No toast for minting in progress (user story is missing, I need to confirm with @KittyLomas)
- [ ] No toast for success
![no-more-toasts](https://user-images.githubusercontent.com/8314736/149743596-04a68407-f1fe-4a52-8b29-052a0f53bf92.gif)

**To Reproduce**
1. Go to https://deploy-preview-380--tracer-pools.netlify.app
2. Follow gifs

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave
 - Version: 1.34.80

**Comment by KittyLomas** [comment]
Hey Elliot, I'll leave some comments re the above:

**Checkbox 1:**
These countdowns are actaully showing two different things. One of them is when the commitment window ends, and the other is for when the user will receive their token. There is a 5 minute period between when the commitment window ends, and when the actual mints / burns are executed (which is called the front-running interval). So this is not actually a bug - it could be clearer on the interface (we do have tooltips explaining this but you have to go looking to find them). 

**Checkbox 2:**
Are you testing this on Arbitrum Testnet? If so yeah, the token prices are around $0 but this won't be an issue on mainnet. But I see how it's an issue for testing. This is worth noting but not necessarily something we need to fix for this release. 

**Checkbox 3:**
I'm not sure this is actually a bug. I think he's followed the brief here. 

**Checkbox 4:**
I agree we should do a minting in progress but I don't think this should block launch of this feature. 

**Checkbox 5:**
We should have a minting success toaster. But I don't think this should block launch.

**Comment by elliot86** [comment]
Closing, as issues have been reallocated.
