### ISSUE TITLE
Remove Static References of USDC

### ISSUE THREAD

**Issue by dospore** [tracer-protocol/pools-client#442]
# Remove Static References of USDC

Make sure that all references of USDC statically are removed or updated to dynamically support new FRAX collateral market.

Fixing amounts to USD vs USDC still makes sure users can see their holdings in USD which is arguably all people want to see. This allows for markets with other collaterals that arent stable coins as well. It is easier for stable coins since the ratio should be 1/1 so the ratio conversion isnt as necessary. To make it compatible for other asses you just need a COLLATERAL/USD price to convert COLLATERAL_VALUE to USD

----
## Acceptance Criteria

- [ ] Ensure that wording in queued commits table is dynamic
- [ ] Ensure that wording in trade history table is dynamic
- [ ] Ensure Token holdings on the portfolio table is 'USD' not fixed to USDC
- [ ] Make sure there is a FRX icon for markets with FRAX not USDC in
- [ ] Make sure there is a USD icon for anything that references USD not USDC

**Comment by issy-fleming** [comment]
Ensure wording in Pools is dynamic: TVL x2 and Token Price
Update token holdings denoted-in options to include another base option icon (FRAX) and replace USDC with USD
Ensure staking table has 'USD' not USDC in relevant headers
Make rewards column in staking table generic header, with TCR or TCR and FXS in row entry
